name: Deploy React App to AWS
on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build React app
        run: npm run build
        env:
          CI: false  # This prevents the build from failing on warnings

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ prod.secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ prod.secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://${{ prod.secrets.AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ prod.secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
